name: "DashLord save action"
description: "Save dashlord results"

inputs:
  url:
    description: URL to save data for
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      id: init
      run: |
        URL=${{ inputs.url }}
        HOSTNAME=$(echo "${{ inputs.url }}" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
        DASHLORD_REPO_PATH=${{ github.workspace }};
        # store results in a folder with then base64 encoded url
        URL_BASE64=$(printf "%s" "$URL" | base64)
        NOW=$(date +"%Y%m%d_%H%M%S")
        OUT_PATH="./results/${URL_BASE64}/${NOW}"

        echo "URL: $URL"
        echo "HOSTNAME: $HOSTNAME"
        echo "DASHLORD_REPO_PATH: $DASHLORD_REPO_PATH"
        echo "NOW: $NOW"
        echo "URL base 64: $URL_BASE64"
        echo "OUT_PATH: $OUT_PATH"

        cd $DASHLORD_REPO_PATH

        mkdir -p $OUT_PATH || true

        ls -la
        ls -la scans

        # filter and jsonify nuclei logs
        if [[ -e "scans/nuclei.log" ]]
        then
          cat scans/nuclei.log | jq -s > scans/nuclei.json || true
          rm scans/nuclei.log || true
        fi

        # rename testssl.sh reports
        # html, json, csv
        for TESTSSL_PATH in "./scans/${HOSTNAME}_p*"; do
          echo "TESTSSL_PATH: $TESTSSL_PATH"
          EXTENSION=`sed 's/^\w\+.//' <<< "$TESTSSL_PATH"`
          echo $EXTENSION
          mv $TESTSSL_PATH ./scans/testssl.${EXTENSION}
        done

        # archive results in dedicated folder
        mv scans/* $OUT_PATH/ || true

        if [[ -e "report_json.json" ]]
        then
          mv report_json.json $OUT_PATH/zap.json
        fi
        if [[ -e "report_md.md" ]]
        then
          mv report_md.md $OUT_PATH/zap.md
        fi
        if [[ -e "report_html.html" ]]
        then
          mv report_html.html $OUT_PATH/zap.html
        fi

        # due to https://github.com/treosh/lighthouse-ci-action/pull/81
        # copy selected reports
        # todo: summarize multiple runs
        if [[ -e "./.lighthouseci" ]]
        then
          for LHR_JSON_PATH in ./.lighthouseci/lhr-*.json; do
              LHR_URL=$(jq -r ".requestedUrl" $LHR_JSON_PATH)
              if [[ "${URL%/}" == "${LHR_URL%/}" ]]
              then
                  LHR_TIMESTAMP=$(basename $LHR_JSON_PATH | sed -e "s/lhr-\([0-9]*\)\.json/\1/")
                  mv .lighthouseci/lhr-${LHR_TIMESTAMP}.json $OUT_PATH/lhr.json
                  mv .lighthouseci/lhr-${LHR_TIMESTAMP}.html $OUT_PATH/lhr.html
              fi
          done
        fi
      
